name: riverpod_async_init_provider
description: A simple command-line application.
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies: 
  riverpod: ^1.0.0-dev.7
  shared_preferences: ^2.0.7

dev_dependencies:
  lints: ^1.0.0
  test: ^1.17.12
